#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2016 Matt Churchyard <churchers@gmail.com>

# get libs
if [ -e "/usr/local/lib/vm-bhyve" ]; then
    LIB="/usr/local/lib/vm-bhyve"
else
    echo "unable to locate vm-bhyve libraries"
    exit 1
fi

# load libs
. "${LIB}/vm-cmd"
. "${LIB}/vm-config"
. "${LIB}/vm-core"
. "${LIB}/vm-datastore"
. "${LIB}/vm-guest"
. "${LIB}/vm-info"
. "${LIB}/vm-migration"
. "${LIB}/vm-rctl"
. "${LIB}/vm-run"
. "${LIB}/vm-switch"
. "${LIB}/vm-util"
. "${LIB}/vm-zfs"

. "${LIB}/vm-base"
